### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by search-ish** [sc1341/TikTok-OSINT#6]
i keep getting this error message. thoughts?

  File "C:\Users\tomca\OneDrive\Pictures\Desktop\TikTok-OSINT-master\tiktokOSINT.py", line 126, in <module>
    main()
  File "C:\Users\tomca\OneDrive\Pictures\Desktop\TikTok-OSINT-master\tiktokOSINT.py", line 122, in main
    tiktok = TikTokOSINT(args.username[0])
  File "C:\Users\tomca\OneDrive\Pictures\Desktop\TikTok-OSINT-master\tiktokOSINT.py", line 32, in __init__
    self.data = self.scrape_profile()
  File "C:\Users\tomca\OneDrive\Pictures\Desktop\TikTok-OSINT-master\tiktokOSINT.py", line 48, in scrape_profile
    content = json.loads(content[0].contents[0])
IndexError: list index out of range

**Comment by C4l1b3r** [comment]
Created by sc1341

Traceback (most recent call last):
  File "/home/kali/TikTok-OSINT/tiktokOSINT.py", line 126, in <module>
    main()
  File "/home/kali/TikTok-OSINT/tiktokOSINT.py", line 119, in main
    tiktok = TikTokOSINT(args.username[0])
  File "/home/kali/TikTok-OSINT/tiktokOSINT.py", line 32, in __init__
    self.data = self.scrape_profile()
  File "/home/kali/TikTok-OSINT/tiktokOSINT.py", line 48, in scrape_profile
    content = json.loads(content[0].contents[0])
IndexError: list index out of range

**Comment by elf-linux** [comment]
File "/home/agordat1977/Downloads/FlareGet/Compressed/TikTok-OSINT-master/tiktokOSINT.py", line 126, in <module>
    main()
  File "/home/agordat1977/Downloads/FlareGet/Compressed/TikTok-OSINT-master/tiktokOSINT.py", line 119, in main
    tiktok = TikTokOSINT(args.username[0])
  File "/home/agordat1977/Downloads/FlareGet/Compressed/TikTok-OSINT-master/tiktokOSINT.py", line 32, in __init__
    self.data = self.scrape_profile()
  File "/home/agordat1977/Downloads/FlareGet/Compressed/TikTok-OSINT-master/tiktokOSINT.py", line 48, in scrape_profile
    content = json.loads(content[0].contents[0])
IndexError: list index out of range
